version: '3'

volumes:
  nextcloud:
  redis:

networks:
  local:
    external: false
  dbs:
    name: mysql_dbs
    external: true
  lofgplv.fr:
    name: lofgplv.fr
    external: true

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    networks:
      local:

  app:
    image: nextcloud:25
    restart: always
    depends_on:
      - redis
    volumes:
      - nextcloud:/var/www/html
    networks:
      local:
      dbs:
      lofgplv.fr:
    environment:
      - MYSQL_PASSWORD=Franca-Nan-jed-Porto-7repayment-Glide9
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mysql-maria-10-1
      - REDIS_HOST=redis

  cron:
    image: nextcloud:25-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      local:
    entrypoint: /cron.sh
    depends_on:
      - redis